services:
  mongo:
    image: mongo:latest
    container_name: "mathpal_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mathpal"
      MONGO_INITDB_ROOT_PASSWORD: "mathpal"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "mathpal-qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always
  
  mq:
    image: rabbitmq:3-management-alpine
    container_name: mathpal-mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    restart: always
  
  data-crawlers:
    image: "mathpal-data-crawlers"
    container_name: mathpal-data-crawlers
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: .docker/Dockerfile.data_crawlers
    env_file:
      - .env
    ports:
      - "9010:8080"
    depends_on:
      - mongo
    networks:
      - local

volumes:
  mongo_data:
  qdrant_data:

networks:
  local:
    driver: bridge