services:
  mongo1:
    image: mongo:5
    container_name: mathpal-mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      - mongo-replica-1-data:/data/db
      - ./.docker/mongo-init.sh:/usr/local/bin/mongo-init.sh:ro
    ports:
      - "30001:30001"
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/mongo-init.sh"]
      interval: 15s
      start_period: 60s
      timeout: 30s
      retries: 5
    networks:
      - local
    restart: always

  mongo2:
    image: mongo:5
    container_name: mathpal-mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    volumes:
      - mongo-replica-2-data:/data/db
      - ./.docker/mongo-init.sh:/usr/local/bin/mongo-init.sh:ro
    ports:
      - "30002:30002"
    networks:
      - local
    restart: always

  mongo3:
    image: mongo:5
    container_name: mathpal-mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    volumes:
      - mongo-replica-3-data:/data/db
      - ./.docker/mongo-init.sh:/usr/local/bin/mongo-init.sh:ro
    ports:
      - "30003:30003"
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "mathpal-qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always
  
  mq:
    image: rabbitmq:3-management-alpine
    container_name: mathpal-mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    restart: always
  
  data-crawlers:
    image: "mathpal-data-crawlers"
    container_name: mathpal-data-crawlers
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: .docker/Dockerfile.data_crawlers
    env_file:
      - .env
    ports:
      - "9010:8080"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - local
  
  data_cdc:
    image: "mathpal-data-cdc"
    container_name: mathpal-data-cdc
    build:
      context: .
      dockerfile: .docker/Dockerfile.data_cdc
    env_file:
      - .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mq
    networks:
      - local

volumes:
  mongo-replica-1-data:
  mongo-replica-2-data:
  mongo-replica-3-data:
  qdrant_data:

networks:
  local:
    driver: bridge