# MathPal Quick Evaluation Configuration
# For fast testing with limited samples

experiment_name: "quick_evaluation"
output_dir: "./evaluation_outputs"

model:
  name: "unsloth/gemma-3n-E2B-it"
  max_seq_length: 2048
  load_in_4bit: true
  load_in_8bit: false
  batch_size: 4
  device: "auto"

generation: # Recommended Gemma-3n generation settings
  max_new_tokens: 512
  temperature: 1.0
  top_p: 0.95
  top_k: 64
  do_sample: true

dataset:
  source: "huggingface"
  dataset_id: "ngohongthai/exam-sixth_grade-instruct-dataset"
  split: "test"
  max_samples: 3  # Quick test with only 3 samples
  instruction_column: "question"
  answer_column: "solution"

evaluation:
  save_predictions: false 
  # Simplified metrics
  metrics:
    opik:
      enabled: true
      metrics: ["answer_relevance", "usefulness"]
    vietnamese_math:
      enabled: true
      metrics: ["mathematical_accuracy", "vietnamese_language_quality"]
    llm_as_judge:
      enabled: false
      metrics: ["accuracy", "completeness", "clarity", "relevance", "helpfulness"]

openrouter:
  base_url: "https://openrouter.ai/api/v1"
  models:
    primary: "openai/gpt-oss-20b:free"
    fallback: "openai/gpt-oss-20b:free"
    judge: "openai/gpt-oss-20b:free"

opik:
  workspace: "mathpal"
  project: "mathpal-gemma3n"


logging:
  level: "DEBUG"
  format: "text"
  output: "console"
